pipeline:
    name: myhelloworld
    identifier: myhelloworld
    projectIdentifier: helloworld
    orgIdentifier: default
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: helloworld
                repoName: https://github.com/personal-bhagi/goHelloWorldServer.git
                build: <+input>
    stages:
        - stage:
              name: Build Test and Push
              identifier: Build_Test_and_Push
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: harnesscluster
                          namespace: harness-delegate
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: Run-unit-tests
                                identifier: Rununittests
                                spec:
                                    connectorRef: helloworlddocker
                                    image: nagisetty1998 / ciquickstart
                                    command: "Image: golang:1.15\r

                                        Command:\r

                                        go get gotest.tools/gotestsum\r

                                        gotestsum --format=standard-verbose --junitfile unit-tests.xml || true\r

                                        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -tags netgo\r

                                        Report Paths: *.xml"
                                    privileged: false
                          - step:
                                type: BuildAndPushDockerRegistry
                                name: Build and push image to docker hub
                                identifier: Build_and_push_image_to_docker_hub
                                spec:
                                    connectorRef: helloworlddocker
                                    repo: nagisetty1998 / ciquickstart
                                    tags:
                                        - <+pipeline.sequenceId>
                                    optimize: true
                  serviceDependencies:
                      - identifier: runhelloworldserver
                        name: run-helloworld-server
                        type: Service
                        spec:
                            connectorRef: helloworlddocker
                            image: helloworld/ciquickstart:<+pipeline.sequenceId
              when:
                  pipelineStatus: All
              variables: []
        - stage:
              name: Run Integration Test
              identifier: Run_Integration_Test
              description: ""
              type: CI
              spec:
                  cloneCodebase: false
                  infrastructure:
                      useFromStage: Build_Test_and_Push
                  serviceDependencies:
                      - identifier: runhelloworldserver
                        name: run-helloworld-server
                        type: Service
                        spec:
                            connectorRef: helloworlddocker
                            image: nagisetty1998 / ciquickstart:<+pipeline.sequenceId>
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: test connection to server
                                identifier: test_connection_to_server
                                spec:
                                    connectorRef: helloworlddocker
                                    image: curlimages/curl:7.73.0
                                    command: "sleep 10\r

                                        curl localhost:8080\r

                                        curl localhost:8080?Hello world!"
                                    privileged: false
              variables: []
